# Generated by Django 5.1 on 2024-11-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('id_categoria', models.CharField(max_length=5)),
                ('id_proveedor', models.CharField(max_length=5)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField()),
                ('talla', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
    ]
